### ISSUE TITLE
Questions Regarding Differentiability and Applicability to Non-Watertight Point Clouds

### ISSUE THREAD

**Issue by Chuan-10** [jsnln/WNNC#1]
Hi,

Thank you so much for sharing this excellent work! I’m relatively new to this field and would greatly appreciate your guidance on a few questions:
1. Is this method differentiable? Would it be suitable to incorporate as a module within an optimization pipeline using PyTorch?
2. Is this approach designed specifically for watertight objects, or could it also be applied to optimize the normals of point clouds in a scene?

Thank you in advance for your time and assistance!

**Comment by Chuan-10** [comment]
I understand that the current implementation may not be directly compatible with PyTorch’s autograd framework. I’ll keep an eye on future updates or have a try by myself.

Thanks for your time and helpful explanation!

**Comment by dongshengLiu** [comment]
@jsnln Hello author, for non-water-tight scenes, such as complex building interiors and streets, what methods can I refer to for reconstructing meshes from unoriented point clouds ?  Thanks.

**Comment by dongshengLiu** [comment]
@jsnln By the way, tested on Armadillo and bunny, the current reconstruction results are of poor quality, looking forward to your updated code ～_～
