### ISSUE TITLE
Strange results of GaussRecon

### ISSUE THREAD

**Issue by Shuenhoy** [jsnln/WNNC#2]
Hi,

Thanks for kindly providing an unofficial implementation of the GaussRecon!  I am very interested in this fast method that could replace PoissonRecon for oriented point clouds.  However, when I tried to run it with an example input from PoissonRecon https://www.cs.jhu.edu/~misha/Code/PoissonRecon/horse.npts , the result looks very strange (red: GaussRecon, white: PoissonRecon):

![image](https://github.com/user-attachments/assets/053afdf2-cee1-4060-a5f2-6717a0615ecb)

I tried to tune the `w` parameter, but it still does not work.
Do you have some ideas about what the issues might be? Or could you share a working input for GaussRecon?

Thanks!

**Comment by jsnln** [comment]
Hi,

Perhaps you are using an older version? For our GR implementation, there is an additional parameter `-a`, which specifies the number of neighbors used for estimating local areas. But in an older version, there was no such parameter and all point areas are set to 1e-5 just for convenience. So this older version doesn't work with highly non-uniform points.

Below is the output of `./main_GaussReconCUDA -i ~/horse.npts -o out.ply -a 32 -w 0.02`, which looks reasonable:

![Screenshot from 2024-10-28 13-55-05](https://github.com/user-attachments/assets/1fe6a088-c899-4fde-866f-074784c3d70e)

Also note that the original GR paper uses a disk integration technique to further improve accuracy, which our implementation doesn't have.

**Comment by jsnln** [comment]
Oops, I just realized I was still doing tests and haven't committed that update here. Please bear with me for some more time.

**Comment by jsnln** [comment]
Hi, sorry for the delay. I've updated the GR code with an area estimation for non-uniform points. Please rebuild the binary executables. This specific example should work well with
```
./main_GaussRecon_cuda -i horse.npts -o horse_out.ply -a 32 -w 0.02
```
